# Generated by Django 5.2.7 on 2025-11-01 12:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TapVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='tapp/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('tap_type', models.CharField(choices=[('T1', 'Type 1'), ('T2', 'Type 2'), ('T3', 'Type 3')], max_length=2)),
            ],
        ),
    ]
