# Generated by Django 5.2.7 on 2025-11-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapvarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
